server:
  port: 8081
spring:
  application:
    name: permission-service
  cloud:
    nacos:
      server-addr: 192.168.150.129:8848
    sentinel:
      eager: true
      transport:
        dashboard: 192.168.150.129:8858
        port: 8719
      http-method-specify: true
  rabbitmq:
    host: 192.168.150.129
    port: 5672
    username: root
    password: 123321
    virtual-host: /
  datasource:
    url: jdbc:mysql://localhost:3306/permission_db?useSSL=false&serverTimezone=UTC
    username: root
    password: '050126'
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xhx.permission.service.entity.pojo
seata:
  registry: # TC服务注册中心的配置，微服务根据这些信息去注册中心获取tc服务地址
    type: nacos # 注册中心类型 nacos
    nacos:
      server-addr: 192.168.150.129:8848 # nacos地址
      namespace: "" # namespace，默认为空
      group: DEFAULT_GROUP # 分组，默认是DEFAULT_GROUP
      application: seata-server # seata服务名称
      username: nacos
      password: nacos
  tx-service-group: my_tx_group # 事务组名称
  service:
    vgroup-mapping: # 事务组与tc集群的映射关系
      my_tx_group: "default"
